### PR TITLE
no_implicit_optional A codemod to make your implicit optional type hints PEP-484 compliant

### PR DESCRIPTION
**Pull request by cleder**
[workerB](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=hsMJTzw)

### CODE REVIEW

**Review by sobolevn — APPROVED** [review]
Nice! Thanks!

**Comment by orsinium** [comment]
We already have [auto-optional](https://github.com/Luttik/auto-optional). I wonder if we should pick one.

**Comment by cleder** [comment]
Good, point, they seem to do the same thing, auto-optional also has a pre-commit plugin.

**Comment by cleder** [comment]
Looking through the code and tests, I tend to lean towards auto-optional, but I may be wrong. (Disclaimer I did not test either yet, I don't have code atm where this would be a problem)

**Comment by orsinium** [comment]
I tried both on a fairly big codebase and no_implicit_optional seemed to fare better. Both tools use libcst under the hood, and in both cases it fails with SyntaxError on some ruff-formatted `with` statements. However, auto-optional stopped formatting files at the first error while no_implicit_optional skipped formatting only for the failing files and says that it formatted the rest. Plus, no_implicit_optional supports the new union syntax

However, in both cases, I don't see any files actually modified, even if the tool says it did. IDK why. Some kind of dry run? 🤔

**Comment by orsinium** [comment]
Lets leave both on the list 👍🏿

**Pull request merged**
