### PR TITLE
Move linter "awesome-lint" into GitHub Action

### PR DESCRIPTION
**Pull request by DmytroLitvinov**
Hi @sobolevn ,

This PR provides moving from Travis CI to GitHub action for running "awesome-lint".
[Here](https://github.com/DmytroLitvinov/awesome-flake8-extensions/pull/46) you can check how it works.

### CODE REVIEW

**Comment by orsinium** [comment]
What's the motivation? The current solution works as intended. The PR doesn't fix a bug and doesn't provide new functionality. Am I missing something?

**Comment by sobolevn** [comment]
Well, moving to GA is a cool thing! I really like it (compared to Travis).
But, we still have it failing. Can you please fix it? @DmytroLitvinov

**Comment by DmytroLitvinov** [comment]
Hi @orsinium , @sobolevn ,

Fixed failed CI.

**Review by sobolevn — APPROVED** [review]

**Comment by sobolevn** [comment]
Thanks a lot! 👍

**Comment by sobolevn** [comment]
Can you please make one more PR with new badge?

**Comment by DmytroLitvinov** [comment]
@sobolevn what badge are we talking about?

**Comment by sobolevn** [comment]
Yes. Here's the code for it:

```md
[![CI](https://github.com/typeddjango/awesome-python-typing/workflows/CI/badge.svg?branch=master&event=push)](https://github.com/typeddjango/awesome-python-typing/actions?query=workflow%3ACI)
```

**Pull request merged**
