### PR TITLE
Update sqlalchemy stubs

### PR DESCRIPTION
**Pull request by wwuck**
The SQLAlchemy project now provides stubs and a mypy plugin.

### CODE REVIEW

**Comment by wwuck** [comment]
Should I have left the existing stubs package in the Readme?  The sqlalchemy docs say their stubs are a complete replacement for the existing dropbox stubs package.

```
These stubs necessarily fully replace the previous sqlalchemy-stubs typing annotations published by Dropbox, as they occupy the same sqlalchemy-stubs namespace as specified by PEP 561.
```

**Comment by orsinium** [comment]
Thank you for your contribution! Yes, let's not replace it for a while and keep both links, please. We can remove `sqlalchemy-stubs` when (and if) they have an official deprecation notice in the readme. Great if you can [open an issue](https://github.com/dropbox/sqlalchemy-stubs/issues) for them to clarify the status of the project.

**Comment by orsinium** [comment]
Related: https://github.com/dropbox/sqlalchemy-stubs/issues/195

**Comment by wwuck** [comment]
Both stubs and plugin for sqlalchemy have the same documentation page which is flagged in CI as a duplicate link.

**Review by sobolevn — APPROVED** [review]
Oh wow, I was not aware about the second one. Thanks!

**Comment by sobolevn** [comment]
> Both stubs and plugin for sqlalchemy have the same documentation page which is flagged in CI as a duplicate link.

You can remove one of them.

**Review by sobolevn — APPROVED** [review]

**Comment by sobolevn** [comment]
Thanks!

**Pull request merged**
