### PR TITLE
Add "Type Check Your Django Application" article

### PR DESCRIPTION
**Pull request by cleder**
add PyTest MonkeyType Introduction and flake8-typing-only-imports

### CODE REVIEW

**Comment by orsinium** [comment]
Thank you! That's a good long-read :)

**Comment by cleder** [comment]
Hey can you label this PR with `hacktoberfest-accepted`, Digital Ocean changed the rules for https://hacktoberfest.digitalocean.com/ so now this is needed to count towards my Tee ;-)

**Comment by orsinium** [comment]
No need, merging should be enough:

> A pull request is considered approved once it has an overall approving review from maintainers, or has been merged by maintainers, or has been given the 'hacktoberfest-accepted' label. 
> https://hacktoberfest.digitalocean.com/faq

Have a good Hacktoberfest :)

**Comment by cleder** [comment]
I think this year the project must have the `hacktoberfest` tag or the PR must have the tag.

GitHub | You've submitted add pytest-pinned to augustogoulart/awesome-pytest | Project not participating

**Comment by orsinium** [comment]
Interesting. 

> GitHub | You've submitted add pytest-pinned to augustogoulart/awesome-pytest | Project not participating

Maybe, this is because your PR in `awesome-pytest` isn't merged yet.

Anyway, I've added the label, just in case. They're free. Now it should be fine :) Let me know if you still have any troubles.

**Pull request merged**
