### PR TITLE
Add `typical` to list of libraries.

### PR DESCRIPTION
**Pull request by seandstewart**
I was linked here from py-slackers. Great to have a list like this! 

This PR adds [typical](https://github.com/seandstewart/typical/) to your list of typing libraries.

### CODE REVIEW

**Comment by orsinium** [comment]
I personally feel bad about weak typing, to be honest. We built a list of tools how to make Python typing better, and this tool makes a step back. It even incompatible with mypy, because you can pass in function anything. The motivation that described in the readme is covered by tools like pydantic (like it does fastapi), and they don't mix up function call with implicit type conversion.

So, I remain it up to the code owner to take the final decision about this PR. On the one hand, it shouldn't be about personal opinions. On the other hand, how else you can build an "awesome list" without opinionated moderation, right?

**Comment by sobolevn** [comment]
@orsinium that's a unique tool in python's ecosystem. I like the variety of tools.
And it's up to the reader to decide what should be used in each particular case.

@seandstewart please, select one category that you feel is the best one for this tool

**Comment by orsinium** [comment]
Good point :+1:

**Comment by seandstewart** [comment]
@orsinium & @sobolevn I've made the changes requested. 

Also, @orsinium, this library features a `strict` mode as well https://typical.seandstewart.io/usage/strict-mode.html

**Comment by sobolevn** [comment]
Thanks a lot!

**Pull request merged**
