### PR TITLE
add dynamic type checkers

### PR DESCRIPTION
**Pull request by orsinium**

### CODE REVIEW

**Comment by orsinium** [comment]
poop on the stick >.< 

> ✖  1:1  Git repository must be at least 30 days old  remark-lint:awesome/git-repo-age

Which line is it?

**Comment by orsinium** [comment]
All repos on the list are incredibly old.

**Comment by sobolevn** [comment]
Thanks! This is about this repo itself. I just want to be notified when the date will come.

**Comment by orsinium** [comment]
Oh, got it. Thank you.

**Pull request merged**
